import json
from datetime import datetime
from pathlib import Path


def generate_report(results: list, output_path: str = "report.html"):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    total = len(results)
    cracked = sum(1 for r in results if r.get("cracked"))
    avg_score = round(sum(r["score"] for r in results) / total, 1) if total else 0

    rows = ""
    for r in results:
        grade_color = {"A":"#39ff14", "B":"#7fff00",
                       "C":"#ffb800", "D":"#ff6b35", "F":"#ff3b3b"}.get(r["grade"], "#aaa")
        cracked_badge = (
            '<span style="color:#ff3b3b;font-weight:700">✗ CRACKED</span>'
            if r.get("cracked") else
            '<span style="color:#39ff14;font-weight:700">✓ Not Found</span>'
        )
        suggestions_html = "<br>".join(r.get("suggestions", []))
        rows += f"""
        <tr>
          <td><code>{r['password']}</code></td>
          <td style="color:{grade_color};font-weight:700;font-size:1.2em">{r['grade']}</td>
          <td>
            <div style="background:#222;border-radius:4px;height:8px;width:100%;min-width:80px">
              <div style="background:{grade_color};height:8px;border-radius:4px;width:{r['score']}%"></div>
            </div>
            <small>{r['score']}/100</small>
          </td>
          <td>{r['entropy']} bits</td>
          <td>{r.get('crack_time','N/A')}</td>
          <td>{cracked_badge}</td>
          <td style="font-size:12px;color:#888">{suggestions_html}</td>
        </tr>"""

    html = f"""<!DOCTYPE html>
<html><head><meta charset="UTF-8">
<title>Password Audit Report — {timestamp}</title>
<style>
  body {{font-family:monospace;background:#0d0d0d;color:#e0e0e0;padding:40px;}}
  h1 {{font-size:2.5em;color:#39ff14;letter-spacing:0.05em;margin-bottom:4px;}}
  .meta {{color:#666;font-size:13px;margin-bottom:32px;}}
  .stats {{display:flex;gap:24px;margin-bottom:32px;}}
  .stat {{background:#141414;border:1px solid #252525;border-radius:8px;padding:16px 24px;text-align:center;}}
  .stat-num {{font-size:2em;font-weight:700;display:block;}}
  .stat-label {{font-size:11px;color:#666;text-transform:uppercase;letter-spacing:0.1em;}}
  table {{width:100%;border-collapse:collapse;background:#141414;border-radius:8px;overflow:hidden;}}
  th {{background:#1a1a1a;color:#666;font-size:11px;text-transform:uppercase;letter-spacing:0.1em;
       padding:12px 16px;text-align:left;border-bottom:1px solid #252525;}}
  td {{padding:12px 16px;border-bottom:1px solid #1a1a1a;vertical-align:middle;}}
  code {{background:#111;border:1px solid #333;padding:2px 8px;border-radius:3px;color:#39ff14;}}
  .footer {{margin-top:32px;color:#444;font-size:12px;}}
</style></head><body>
<h1>🔐 PASSWORD AUDIT REPORT</h1>
<div class="meta">Generated: {timestamp} | Total tested: {total}</div>
<div class="stats">
  <div class="stat"><span class="stat-num" style="color:#ff3b3b">{cracked}</span><span class="stat-label">Cracked</span></div>
  <div class="stat"><span class="stat-num" style="color:#39ff14">{total - cracked}</span><span class="stat-label">Survived</span></div>
  <div class="stat"><span class="stat-num" style="color:#ffb800">{avg_score}</span><span class="stat-label">Avg Score</span></div>
</div>
<table>
  <tr><th>Password</th><th>Grade</th><th>Score</th><th>Entropy</th>
      <th>MD5 Crack Time</th><th>Dictionary</th><th>Suggestions</th></tr>
{rows}
</table>
<div class="footer">Generated by Password Auditor — for authorized security testing only.</div>
</body></html>"""

    Path(output_path).write_text(html, encoding="utf-8")
    return output_path